config/routes.rb
Rails.application.routes.draw do
  get 'welcom/index'

  get 'welcom/about'

  get 'welcom/contact'

  get 'welcom/faqs'

  resources :charges
  resources :postcodes
  resources :payments
  resources :deliveries
  resources :bouquets
  root :to => 'home#index'
  devise_for :users
  

end

app/models/bouquet.rb
class Bouquet < ActiveRecord::Base
end

app/controllers/bouquets_controller.rb
class BouquetsController < ApplicationController
  before_action :set_bouquet, only: [:show, :edit, :update, :destroy]

  # GET /bouquets
  # GET /bouquets.json
  def index
    @bouquets = Bouquet.all
  end

  # GET /bouquets/1
  # GET /bouquets/1.json
  def show
  end

  # GET /bouquets/new
  def new
    @bouquet = Bouquet.new
  end

  # GET /bouquets/1/edit
  def edit
  end

  # POST /bouquets
  # POST /bouquets.json
  def create
    @bouquet = Bouquet.new(bouquet_params)

    respond_to do |format|
      if @bouquet.save
        format.html { redirect_to @bouquet, notice: 'Bouquet was successfully created.' }
        format.json { render :show, status: :created, location: @bouquet }
      else
        format.html { render :new }
        format.json { render json: @bouquet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bouquets/1
  # PATCH/PUT /bouquets/1.json
  def update
    respond_to do |format|
      if @bouquet.update(bouquet_params)
        format.html { redirect_to @bouquet, notice: 'Bouquet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bouquet }
      else
        format.html { render :edit }
        format.json { render json: @bouquet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bouquets/1
  # DELETE /bouquets/1.json
  def destroy
    @bouquet.destroy
    respond_to do |format|
      format.html { redirect_to bouquets_url, notice: 'Bouquet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bouquet
      @bouquet = Bouquet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bouquet_params
      params.require(:bouquet).permit(:style, :description, :image_url, :price, :size)
    end
end

app/helpers/bouquets_helper.rb
module BouquetsHelper
end

app/views/bouquets/_form.html.erb
<%= form_for(@bouquet) do |f| %>
  <% if @bouquet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bouquet.errors.count, "error") %> prohibited this bouquet from being saved:</h2>

      <ul>
      <% @bouquet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bouquets/edit.html.erb
<h1>Editing Bouquet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bouquet %> |
<%= link_to 'Back', bouquets_path %>

app/views/bouquets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bouquets</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
  
  <thead>
    <tr>
      <th>Style</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bouquets.each do |bouquet| %>
      <tr>
        <td><%= bouquet.style %></td>
        <td><%= bouquet.description %></td>
        <td><%= bouquet.image_url %></td>
        <td><%= bouquet.price %></td>
        <td><%= bouquet.size %></td>
        <td><%= link_to 'Show', bouquet, class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_bouquet_path(bouquet), class: 'btn btn-mini btn-sucess'  %></td>
        <td><%= link_to 'Destroy', bouquet, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Bouquet', new_bouquet_path %>

app/views/bouquets/new.html.erb
<h1>New Bouquet</h1>

<%= render 'form' %>

<%= link_to 'Back', bouquets_path %>

app/views/bouquets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Style:</strong>
  <%= @bouquet.style %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bouquet.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @bouquet.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bouquet.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @bouquet.size %>
</p>

<%= link_to 'Edit', edit_bouquet_path(@bouquet) %> |
<%= link_to 'Back', bouquets_path %>