config/routes.rb
Rails.application.routes.draw do
  get 'welcom/index'

  get 'welcom/about'

  get 'welcom/contact'

  get 'welcom/faqs'

  resources :charges
  resources :postcodes
  resources :payments
  resources :deliveries
  resources :bouquets
  root :to => 'home#index'
  devise_for :users
  

end

app/models/postcode.rb
class Postcode < ActiveRecord::Base
end

app/controllers/postcodes_controller.rb
class PostcodesController < ApplicationController
  before_action :set_postcode, only: [:show, :edit, :update, :destroy]

  # GET /postcodes
  # GET /postcodes.json
  def index
    @postcodes = Postcode.all
  end

  # GET /postcodes/1
  # GET /postcodes/1.json
  def show
  end

  # GET /postcodes/new
  def new
    @postcode = Postcode.new
  end

  # GET /postcodes/1/edit
  def edit
  end

  # POST /postcodes
  # POST /postcodes.json
  def create
    @postcode = Postcode.new(postcode_params)

    respond_to do |format|
      if @postcode.save
        format.html { redirect_to @postcode, notice: 'Postcode was successfully created.' }
        format.json { render :show, status: :created, location: @postcode }
      else
        format.html { render :new }
        format.json { render json: @postcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postcodes/1
  # PATCH/PUT /postcodes/1.json
  def update
    respond_to do |format|
      if @postcode.update(postcode_params)
        format.html { redirect_to @postcode, notice: 'Postcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @postcode }
      else
        format.html { render :edit }
        format.json { render json: @postcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postcodes/1
  # DELETE /postcodes/1.json
  def destroy
    @postcode.destroy
    respond_to do |format|
      format.html { redirect_to postcodes_url, notice: 'Postcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postcode
      @postcode = Postcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postcode_params
      params.require(:postcode).permit(:postcode, :email)
    end
end

app/helpers/postcodes_helper.rb
module PostcodesHelper
end

app/views/postcodes/_form.html.erb
<%= form_for(@postcode) do |f| %>
  <% if @postcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postcode.errors.count, "error") %> prohibited this postcode from being saved:</h2>

      <ul>
      <% @postcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postcodes/edit.html.erb
<h1>Editing Postcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @postcode %> |
<%= link_to 'Back', postcodes_path %>

app/views/postcodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Postcodes</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
<table>
  <thead>
    <tr>
      <th>Postcode</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postcodes.each do |postcode| %>
      <tr>
        <td><%= postcode.postcode %></td>
        <td><%= postcode.email %></td>
        <td><%= link_to 'Show', postcode,class: 'btn btn-mini btn-danger' %></td>
        <td><%= link_to 'Edit', edit_postcode_path(postcode),class: 'btn btn-mini btn-sucess' %></td>
        <td><%= link_to 'Destroy', postcode, method: :delete,class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Postcode', new_postcode_path %>

app/views/postcodes/new.html.erb
<h1>New Postcode</h1>

<%= render 'form' %>

<%= link_to 'Back', postcodes_path %>

app/views/postcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Postcode:</strong>
  <%= @postcode.postcode %>
</p>

<p>
  <strong>Email:</strong>
  <%= @postcode.email %>
</p>

<%= link_to 'Edit', edit_postcode_path(@postcode) %> |
<%= link_to 'Back', postcodes_path %>