config/routes.rb
Rails.application.routes.draw do
  get 'welcom/index'

  get 'welcom/about'

  get 'welcom/contact'

  get 'welcom/faqs'

  resources :charges
  resources :postcodes
  resources :payments
  resources :deliveries
  resources :bouquets
  root :to => 'home#index'
  devise_for :users
  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Online Flower Bouquets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<div id='header'>
	  <img src="pulpitrock.jpg" alt="Mountain View">
	</div>
  <%= render 'layouts/header' %>
	<div id='menu'>
	 <div id='navbar'>
	 

		<%= link_to "Home", root_path %>
		<%= link_to "Bouquets", bouquets_path %>
		<%= link_to "Postcode", postcodes_path %>
		<%= link_to "Delivery", deliveries_path %>
		<%= link_to "Payment", payments_path %>


	  </div>
	 </div>
	  
	  <div id='container'>
	  
		<div id='content'>
		
		

		<%= yield %>
		</div>

	  </div>

	<div id='first-column'>
	   <div class="loginbox">
	   

			<% if user_signed_in? %>
				<h2>Sign in as ...<%current_user.email %>
				  (<%= link_to 'Sign out' , destroy_user_sessions_path,
							:method => :delete%>
				</h2>                  
		  
			  <% else %>
				<h2> <%= link_to 'Register' , new_user_registration_path %> 
		  
				</h2>
		  
				<h2> <%= link_to 'Sign in' , new_user_session_path %>
		  
				</h2>
		  
			  <% end %>
		  </div>
	</div>


	<div id='footer'>
	  <h6 class="footertext">&copy;Flowers Online :2017</h6>
	  
	 </div>


</body>
</html>